In [1]:
import numpy as np

Think of it like this, if you give meshgrid 2 arrays: x and y, you're asking: give me all (x, y) arranged in a grid form. 

Consider the example below, if I wrote the pairs myself, I'd have: 

```python
[(1, 10), (2, 10), (3, 10),
 (1, 20), (2, 20), (3, 30)]


In [3]:
x = [1, 2, 3]
y = [10, 20]

X, Y = np.meshgrid(x, y)
np.meshgrid(x, y)

(array([[1, 2, 3],
        [1, 2, 3]]),
 array([[10, 10, 10],
        [20, 20, 20]]))

In [7]:
pairs = X.flatten(), Y.flatten()
pairs

(array([1, 2, 3, 1, 2, 3]), array([10, 10, 10, 20, 20, 20]))

In [12]:
np.stack(pairs, axis=1)

array([[ 1, 10],
       [ 2, 10],
       [ 3, 10],
       [ 1, 20],
       [ 2, 20],
       [ 3, 20]])